apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: auto-scaler
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source: 
    repoURL: https://github.com/ManhTrinhNguyen/GitOps.git
    targetRevision: HEAD
    path: ./auto-scaler
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true